font_family JetBrainsMono Nerd Font
font_size 10
confirm_os_window_close 0

shell_integration enabled

background #040813
foreground #ffffff

cursor_shape beam
cursor_blink_interval 0.5

background_opacity 0.64

map ctrl+shift+left no_op
map ctrl+shift+right no_op
map ctrl+shift+home no_op
map ctrl+shift+end no_op